#!/usr/bin/env python3
# File:  generate_tptp.py
# Author:  mikolas
# Created on:  Thu Jul 31 10:15:36 CEST 2025
# Copyright (C) 2025, Mikolas Janota
import argparse
import sys
from datetime import datetime

import generate_eqs_list


def run_main():
    """Run main."""
    arg_parser = argparse.ArgumentParser()
    arg_parser.add_argument(
        "left",
        help="id of left equation",
        type=int,
    )
    arg_parser.add_argument(
        "right",
        help="id of right equation",
        type=int,
    )
    args = arg_parser.parse_args()
    print(print_tptp_file(args.left, args.right))


class Converter:
    """Utility for converting equations to tptp expressions."""

    def __init__(self, m_name, var_names):
        self.var_names = var_names
        self.m_name = m_name

    def tup_to_term(self, tup):
        """Make term out of a pair."""
        if isinstance(tup, int):
            return self.var_names[tup]
        if isinstance(tup, tuple):
            assert len(tup) == 2
            params = ", ".join(map(self.tup_to_term, tup))
            return f"{self.m_name}({params})"
        raise ValueError("Expected an int or a tuple")

    def tup_to_eq(self, tup, negate):
        """Produce a tptp equation out of an equation."""
        assert len(tup) == 2
        left, right = map(self.tup_to_term, tup)
        return f"{left} {'!=' if negate else '='} {right}"


def print_tptp_file(left, right):
    """Print the whole tptp file."""
    tup_l = generate_eqs_list.eqs[left - 1]
    tup_r = generate_eqs_list.eqs[right - 1]
    varnames = "XYZWUVRST"
    constnames = "abcdrstkv"
    convl = Converter("m", varnames)
    convr = Converter("m", constnames)
    left_eq = convl.tup_to_eq(tup_l, negate=False)
    right_eq = convr.tup_to_eq(tup_r, negate=True)
    return f"""\
% generated by {sys.argv[0]} on {datetime.today().strftime('%Y-%m-%d')}
% {left} AND NOT {right}
% {left_eq} AND NOT {convl.tup_to_eq(tup_r, negate=False)}
cnf(left, axiom,
    {left_eq} ).

cnf(right, negated_conjecture,
    {right_eq} ).
"""


if __name__ == "__main__":
    run_main()
