#!/usr/bin/env python3
"""This scripts allows given a left_eqn and a right_eqn, to generate an SMT2
file to look for a counterexample to left_eqn => right_eqn, i.e. look for
left_eqn AND NOT right_eqn.

This script requires the Z3 python bindings and passing in the equation
numbers on the command line. It depends on the `generate_eqs_list`
script.
"""
__author__ = "Mikolas Janota"
__copyright__ = "2025, Mikolas Janota"

import argparse
import sys
from datetime import datetime
from os.path import basename

from z3 import (
    Const,
    DeclareSort,
    Exists,
    ExprRef,
    ForAll,
    Function,
    IntSort,
    Not,
    Solver,
    is_const,
)

import generate_eqs_list
from generate_eqs_list import eqs


class Converter:
    """Utility for converting equations to z3 expressions."""

    def __init__(self, the_m, the_sort, var_names):
        self.the_m = the_m
        self.the_sort = the_sort
        self.var_names = var_names

    def tup_to_term(self, tup):
        """Make term out of a pair."""
        if isinstance(tup, int):
            return Const(self.var_names[tup], self.the_sort)
        if isinstance(tup, tuple):
            assert len(tup) == 2
            return self.the_m(self.tup_to_term(tup[0]), self.tup_to_term(tup[1]))
        raise ValueError("Expected an int or a tuple")

    def eqn_to_z3(self, tup):
        """Produce a z3 equation out of an equation."""
        assert len(tup) == 2
        left, right = tup
        return self.tup_to_term(left) == self.tup_to_term(right)


def get_vars(t: ExprRef):
    """Get vars from a z3 expression."""
    all_vars = set()
    if is_const(t):
        all_vars.add(t)
    else:
        for u in t.children():
            all_vars = all_vars.union(get_vars(u))
    return all_vars


def mk_univ(t: ExprRef):
    """Universal closure of t."""
    return ForAll(list(get_vars(t)), t)


def mk_exists(t: ExprRef):
    """Existential closure of t."""
    return Exists(list(get_vars(t)), t)


def term2str(tup, top=False):
    vars = "xyzwuvrst"
    if isinstance(tup, int):
        return vars[tup]
    if isinstance(tup, tuple):
        assert len(tup) == 2
        x, y = tup
        rv = f"{term2str(x)}{term2str(y)}"
        return rv if top else f"({rv})"
    raise ValueError("Expected an int or a tuple")
    return None


def format_eq(e):
    """Turn equation into a string, for printing only."""
    assert isinstance(e, tuple) and len(e) == 2
    return f"{term2str(e[0], True)} = {term2str(e[1], True)}"


def print_smt2_file(left, right, m, thesort, logic, skolemize):
    """Print the whole smt2 file."""
    tup_l = eqs[left - 1]
    tup_r = eqs[right - 1]
    conv = Converter(m, thesort, generate_eqs_list.VAR_NAMES)
    left_eq = conv.eqn_to_z3(tup_l)
    s = Solver()
    s.add(mk_univ(left_eq))
    if skolemize:
        conv_sk = Converter(m, thesort, "abcdrstkv")
        right_eq = conv_sk.eqn_to_z3(tup_r)
        s.add(Not(right_eq))
    else:
        right_eq = conv.eqn_to_z3(tup_r)
        s.add(mk_exists(Not(right_eq)))
    return f"""\
; generated by {basename(sys.argv[0])} on {datetime.today().strftime('%Y-%m-%d')}
; {left} AND NOT {right}
; {format_eq(tup_l)} AND not {format_eq(tup_r)}
(set-logic {logic})
{s.to_smt2()}"""


def mk_decls(use_ints):
    """Makes the z3 declarations."""
    thesort = IntSort() if use_ints else DeclareSort("S")
    m = Function("m", thesort, thesort, thesort)
    return thesort, m


def run_main():
    """Run main."""
    arg_parser = argparse.ArgumentParser()
    arg_parser.add_argument(
        "left",
        help="id of left equation",
        type=int,
    )
    arg_parser.add_argument(
        "right",
        help="id of right equation",
        type=int,
    )
    arg_parser.add_argument("-i", "--ints", help="use ints", action="store_true")
    arg_parser.add_argument(
        "-s", "--skolemize", help="skolemize the exist part", action="store_true"
    )
    args = arg_parser.parse_args()
    thesort, m = mk_decls(args.ints)
    logic = "UFLIA" if args.ints else "UF"
    print(print_smt2_file(args.left, args.right, m, thesort, logic, args.skolemize))


if __name__ == "__main__":
    run_main()
