#!/usr/bin/env python3
# File:  generate_sygus.py
# Author:  mikolas
# Created on:  Sun Aug 10 14:24:45 BST 2025
# Copyright (C) 2025, Mikolas Janota
"""This scripts allows given a left_eqn and a right_eqn, to generate a SYGUS.

file to look for a counterexample to left_eqn => right_eqn, i.e. look
for left_eqn AND NOT right_eqn.
"""
__author__ = "Mikolas Janota"
__copyright__ = "2025, Mikolas Janota"

import argparse
import sys
from datetime import datetime
from os.path import basename

from generate_eqs_list import eqs
from generate_smt2 import format_eq


def run_main():
    """Run main."""
    arg_parser = argparse.ArgumentParser()
    arg_parser.add_argument(
        "left",
        help="id of left equation",
        type=int,
    )
    arg_parser.add_argument(
        "right",
        help="id of right equation",
        type=int,
    )
    args = arg_parser.parse_args()
    print(mk_sygus_file(args.left, args.right, "m"))


class Converter:
    """Utility for converting equations to sygus expressions."""

    def __init__(self, m_name, var_names):
        self.var_names = var_names
        self.m_name = m_name

    def tup2str(self, tup):
        """Make term out of a pair."""
        if isinstance(tup, int):
            return self.var_names[tup]
        if isinstance(tup, tuple):
            assert len(tup) == 2
            params = " ".join(map(self.tup2str, tup))
            return f"({self.m_name} {params})"
        raise ValueError("Expected an int or a tuple")

    def eq2str(self, tup, negate):
        """Produce a tptp equation out of an equation."""
        assert len(tup) == 2
        left, right = map(self.tup2str, tup)
        rv = f"(= {left} {right})"
        return f"(not {rv})" if negate else rv


def get_free(tup):
    """Get free variables of tup."""
    if isinstance(tup, int):
        return {tup}
    if isinstance(tup, tuple):
        assert len(tup) == 2
        return set().union(*(get_free(a) for a in tup))
    raise ValueError("Expected an int or a tuple")


def mk_sygus_file(left, right, m):
    """Print the whole smt2 file."""
    lhs = eqs[left - 1]
    rhs = eqs[right - 1]
    flhs = get_free(lhs)
    frhs = get_free(rhs)
    logic = "LIA"
    cons = "abcdrstkv"
    vnames = "xyzwuvrst"
    lconv = Converter(m, vnames)
    rconv = Converter(m, cons)
    const_decls = "\n".join([f"(synth-fun {cons[v]} () Int)" for v in frhs])
    fa_decls = "\n".join([f"(declare-var {vnames[v]} Int)" for v in flhs])

    return f"""\
; generated by {basename(sys.argv[0])} on {datetime.today().strftime('%Y-%m-%d')}
; {left} AND NOT {right}
; {format_eq(lhs)} AND NOT {format_eq(rhs)}
(set-logic {logic})
(synth-fun {m} ((x Int) (y Int)) Int)
{const_decls}
{fa_decls}
(constraint {rconv.eq2str(rhs, negate=True)})
(constraint {lconv.eq2str(lhs, negate=False)})
(check-synth)
"""


if __name__ == "__main__":
    run_main()
